spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rabam
    username: postgres
    password: l8n3_a7-c2.E

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    enabled: true
